version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.4.1
        working_directory: ~/project
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - run:
                name: NPM install
                command: npm install
            - run
                name: NPM run build
                command npm run build-prod