version: 2
jobs:
    build:
        docker:
            - image: circleci/ruby:2.4.1
        working_directory: ~/project
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}